### ISSUE TITLE
MITRemActDate attribute rule error

### ISSUE THREAD

**Issue by CanDKD** [uic-utah/uic-attribute-rules#119]
This AR only works if the Remedial Action Date is before the MITDate.  Remedial Action Date needs to be AFTER the MITDate.  Brianna discovered this by entering an MITRemActDate before the MITDate and the AR accepted it.

![image](https://user-images.githubusercontent.com/4369080/70757700-cf649300-1cfd-11ea-8bd2-3f672dd8eff9.png)

**Comment by steveoh** [comment]
how did she enter it and what values did she use?

for example,

```js
const earliestDate = new Date('2019-12-18');
const mitremactdate = new Date('2018-12-02');
const mitdate = new Date('2019-11-10');

if (mitremactdate < earliestDate && mitremactdate > mitdate) {
	console.log('bingo')
} else {
	console.log('wrong')
}
```

gives the correct result which matches the existing ar rule.

Now this sounds like what she did. Notice the `2018` year. This prints wrong. 

```js
const earliestDate = new Date('2019-12-18');
const mitremactdate = new Date('2018-12-02');
const mitdate = new Date('2019-11-10');

if (mitremactdate < earliestDate && mitremactdate > mitdate) {
	console.log('bingo')
} else {
	console.log('wrong')
}
```

This AR rule is only run on an update so was she able to enter this as an insert?

**Comment by rsparker-utah** [comment]
Good Morning Steve,

Candace retired yesterday, so I will try to answer your question about the above issue. I spoke with Brianna to get some more background information on this issue. When she enters a mitremactdate that is after the mitdate she gets the following:

![image](https://user-images.githubusercontent.com/49735267/71192655-ef3c0f80-2245-11ea-8059-bf1f8782e5fb.png)

Conversely, when she enters a mitremactdate that is before the mitdate she gets the following:

![image](https://user-images.githubusercontent.com/49735267/71192678-fa8f3b00-2245-11ea-92ef-ab7e070040e9.png)

The script error message appears to be correct, but the AR is triggering incorrectly. I am still trying to fully learn the processes/verbiage involved in this UIC database, so I apologize if my articulation of this issue is somewhat basic. Thank you for patience. Please let me know if you need any additional information.

**Comment by steveoh** [comment]
Thanks, let me take another look at it with your information!

**Comment by steveoh** [comment]
thanks @rsparker-utah! I updated your staging environment. Will you test and let me know when is a good time to promote that to production?

**Comment by rsparker-utah** [comment]
Great thank you @steveoh I am out of the office on annual leave for the holidays through January 6th, but I will look into testing when I return. Thank you and Happy Holidays!

**Comment by rsparker-utah** [comment]
Hi @steveoh 

Brianna helped me test the above in development and it looks like the attribute rule is triggering correctly, so we should be good to promote this to production.  Is there anything that needs to be done before a change is promoted from development to production? For example, do I have to make sure that no one is actively using the database before the promotion can occur?

**Comment by steveoh** [comment]
I will need an exclusive lock to perform the migration. I do not think that versions need to be reconciled.

**Comment by rsparker-utah** [comment]
Ok, do I need to do anything on my end to ensure you can get an exclusive lock (e.g., make sure no one else is actively using the database, etc)?

**Comment by steveoh** [comment]
Yeah, scheduling a time when no one is connected should be good.

**Comment by rsparker-utah** [comment]
Ok, what is your schedule looking like for the rest of the week? Is there a time that would work for you?

**Comment by steveoh** [comment]
I am pretty free today through thursday to do this.

**Comment by rsparker-utah** [comment]
Would Thursday at 1:30pm work for you (we could also do anytime after 1:30 pm as well if that would be better for you)? Also, about how long should we plan to stay out of the database while this promotion is in process?

**Comment by steveoh** [comment]
I updated the rules. You're all set. I hope you don't mind I didn't wait until thursday 🏁

**Comment by rsparker-utah** [comment]
Excellent! We don't mind at all, thanks @steveoh !
